#!/usr/bin/env bash
#
# ORBIT — repo bootstrap
# Elite Event Hub · Laravel + Livewire + Alpine + Tailwind
#
# Run this ONCE from your repo root, before you open Claude Code.
# It does the two things that must not be done by hand:
#
#   1. Extracts the design tokens and component CSS out of the design
#      system HTML, byte for byte. 72 tokens and 140 component classes
#      across 261 rules. An agent retyping those will introduce silent
#      errors, and every wrong hex quietly breaks a verified contrast
#      guarantee.
#
#   2. Writes CLAUDE.md guardrails so the rules survive after you stop
#      watching the agent.
#
# It does NOT write any Blade, PHP or JS. That is Claude Code's job.
#
#   ./setup-orbit.sh              normal run
#   ./setup-orbit.sh --force      overwrite files that already exist
#   ./setup-orbit.sh --check      verify only, change nothing
#
set -euo pipefail

HTML="orbit-system.html"
FORCE=0
CHECK=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --check) CHECK=1 ;;
    -h|--help) sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

bold=$'\033[1m'; dim=$'\033[2m'; grn=$'\033[32m'; ylw=$'\033[33m'; red=$'\033[31m'; off=$'\033[0m'
say()  { printf '%s\n' "$*"; }
ok()   { printf '  %s✓%s %s\n' "$grn" "$off" "$*"; }
warn() { printf '  %s!%s %s\n' "$ylw" "$off" "$*"; }
die()  { printf '\n%serror:%s %s\n' "$red" "$off" "$*" >&2; exit 1; }

say ""
say "${bold}ORBIT — repo bootstrap${off}"
say "${dim}light-first · gold accent · extracts CSS, writes guardrails, touches nothing else${off}"
say ""

# ── 1. sanity ────────────────────────────────────────────────────────
say "${bold}Checking the repo${off}"

[ -f artisan ]       || die "no artisan file here. Run this from your Laravel repo root."
[ -f "$HTML" ]       || die "$HTML not found. Copy it into the repo root first."
[ -d resources/css ] || die "resources/css/ missing. Is this a standard Laravel app?"
ok "Laravel repo detected"
ok "$HTML found ($(wc -c < "$HTML" | tr -d ' ') bytes)"

if git rev-parse --git-dir >/dev/null 2>&1; then
  if [ -n "$(git status --porcelain)" ]; then
    warn "working tree is dirty"
    if [ "$CHECK" -eq 0 ] && [ "$FORCE" -eq 0 ]; then
      die "refusing to write into a dirty tree so you can always undo this.
       Commit or stash first, or re-run with --force if you know what you are doing."
    fi
  else
    ok "git working tree is clean"
  fi
else
  warn "not a git repo — you will not be able to undo this easily"
fi

# ── 2. extract ───────────────────────────────────────────────────────
TOK_START=':root, [data-theme="light"]{'
CMP_START='*,*::before,*::after{box-sizing'
CMP_STOP='.doc{display:grid;grid-template-columns:262px'

extract () { # $1 start marker, $2 stop marker
  awk -v start="$1" -v stop="$2" '
    index($0, start) { f = 1 }
    index($0, stop)  { f = 0 }
    f { print }
  ' "$HTML"
}

TOKENS="$(extract "$TOK_START" "$CMP_START")"
COMPS="$(extract "$CMP_START" "$CMP_STOP")"

[ -n "$TOKENS" ] || die "could not find the token block in $HTML — is it the ORBIT system file?"
[ -n "$COMPS"  ] || die "could not find the component block in $HTML — is it the ORBIT system file?"

TOKEN_COUNT=$(printf '%s' "$TOKENS" | grep -o -- '--[a-z0-9-]*:' | sort -u | wc -l | tr -d ' ')
CLASS_COUNT=$(printf '%s' "$COMPS" | grep -o -- '\.o-[a-z0-9_-]*' | sort -u | wc -l | tr -d ' ')
RULE_COUNT=$(printf '%s' "$COMPS" | grep -c '{' | tr -d ' ')

say ""
say "${bold}Extracted from the design system${off}"
ok "$TOKEN_COUNT design tokens"
ok "$CLASS_COUNT component classes"
ok "$RULE_COUNT CSS rules"

if [ "$CHECK" -eq 1 ]; then
  say ""
  say "${dim}--check: nothing written.${off}"
  exit 0
fi

# ── 3. write ─────────────────────────────────────────────────────────
write () { # $1 path, body on stdin
  local path="$1"
  if [ -f "$path" ] && [ "$FORCE" -eq 0 ]; then
    warn "$path exists — skipped (use --force to overwrite)"
    cat > /dev/null
    return
  fi
  mkdir -p "$(dirname "$path")"
  cat > "$path"
  ok "wrote $path"
}

say ""
say "${bold}Writing files${off}"

{
  cat <<'HDR'
/* ═══════════════════════════════════════════════════════════════════════
   ORBIT DESIGN SYSTEM — TOKENS
   GENERATED by setup-orbit.sh from orbit-system.html
   Do not edit by hand. Edit the HTML and re-run the script.
   ─────────────────────────────────────────────────────────────────────
   LIGHT IS THE DEFAULT. Both themes define IDENTICAL variable names,
   so no component ever needs a dark variant. Switch by setting
   data-theme="dark" on <html>. Nothing else.

   TWO GOLDS, and they are NOT interchangeable:
     --gold      #8A6209  text, icons, labels. 5.48:1 on white.
     --gold-lit  #E8B84B  fills, rings, active states. Dark text on it.
   --gold-lit as text on a light surface is 1.69:1. Never do it.
   Every signal colour follows the same pattern: --vital reads,
   --vital-lit fills.

   DO NOT CHANGE COLOUR VALUES. 27 text pairs measured per theme, all
   at or above 4.5:1. Changing one hex breaks that silently.
   ═══════════════════════════════════════════════════════════════════ */

HDR
  printf '%s\n' "$TOKENS"
} | write resources/css/orbit-tokens.css

{
  cat <<'HDR'
/* ═══════════════════════════════════════════════════════════════════════
   ORBIT DESIGN SYSTEM — COMPONENTS
   GENERATED by setup-orbit.sh from orbit-system.html
   Do not edit by hand. Edit the HTML and re-run the script.
   ─────────────────────────────────────────────────────────────────────
   Requires orbit-tokens.css to be imported first.
   Class prefix: .o-
   If you need a value that is not a token, the answer is a new token,
   not a literal.
   ═══════════════════════════════════════════════════════════════════ */

HDR
  printf '%s\n' "$COMPS"
} | write resources/css/orbit.css

write resources/css/orbit-theme.css <<'EOF'
/* Tailwind wiring — import AFTER tailwindcss in app.css.
   Exposes ORBIT tokens as Tailwind theme values so utilities and
   components read from one source.

   Note the -lit pairs: --color-gold is the READ colour, --color-gold-lit
   is the FILL colour. Same for every signal. Using the wrong one is the
   single most common mistake in this system. */

@theme {
  --color-canvas:   var(--abyss);
  --color-surface:  var(--hull);
  --color-raised:   var(--deck);
  --color-rim:      var(--rim);
  --color-rim-hi:   var(--rim-hi);
  --color-chrome:   var(--chrome);

  --color-ink:      var(--ink);
  --color-ink-2:    var(--ink-2);
  --color-ink-3:    var(--ink-3);
  --color-ink-4:    var(--ink-4);

  --color-gold:         var(--gold);        /* text / icon */
  --color-gold-lit:     var(--gold-lit);    /* fill / ring / active */
  --color-vital:        var(--vital);
  --color-vital-lit:    var(--vital-lit);
  --color-ion:          var(--ion);
  --color-ion-lit:      var(--ion-lit);
  --color-plasma:       var(--plasma);
  --color-plasma-lit:   var(--plasma-lit);
  --color-flare:        var(--flare);
  --color-flare-lit:    var(--flare-lit);
  --color-critical:     var(--critical);
  --color-critical-lit: var(--critical-lit);

  --font-display: 'Instrument Serif', Georgia, serif;
  --font-sans:    'Inter', system-ui, -apple-system, sans-serif;
  --font-mono:    'JetBrains Mono', ui-monospace, SFMono-Regular, monospace;

  --radius-xs: 8px;  --radius-sm: 11px; --radius-md: 16px;
  --radius-lg: 22px; --radius-xl: 30px;
}

/* Documents always print light and without chrome. */
@media print {
  html { --void:#fff; --abyss:#fff; --hull:#fff; --plate:#fff; --deck:#fff; }
  .o-arc, .o-dock, .o-topbar, .o-kpistrip, .o-quick { display: none !important; }
  .o-panel, .o-card { box-shadow: none !important; break-inside: avoid; }
  .o-task { break-inside: avoid; }
}
EOF

write CLAUDE.md <<'EOF'
# Elite Event Hub — working agreement

## Design system: ORBIT

The visual specification is `orbit-system.html` in the repo root.
Open it in a browser — it is live and interactive — and read the CSS in
its `<style>` block. That file is the source of truth for every colour,
size, radius, shadow and class name. Section 09 is the target layout.

`resources/css/orbit-tokens.css` and `resources/css/orbit.css` are
**generated** from that HTML by `setup-orbit.sh`. Never edit them by hand.
If a token genuinely needs to change, change the HTML and re-run the script.

### The five laws

1. **One light source.** Gold marks the action, the position, the one number.
2. **Distance is relevance.** Modules orbit the event core.
3. **Light is home.** Dark is a mode you enter for show days.
4. **Numbers are typography.** Every figure in the data face.
5. **Stillness is a feature.** Motion means state changed.

### The two golds — the rule most likely to be broken

- `--gold` **#8A6209** — text, icons, labels. Passes AA on light surfaces.
- `--gold-lit` **#E8B84B** — fills, rings, active states, dock highlight.
  Carries dark text at 9.16:1. As text on a light surface it is 1.69:1.
  **Never use --gold-lit as a text colour.**

Every signal colour follows the same pattern: `--vital` reads,
`--vital-lit` fills. Same for ion, plasma, flare, critical.

### Hard rules

- Never introduce a colour, radius, shadow, font-size, spacing value or
  transition duration that is not already a token.
- Gold appears on at most **three** elements per viewport.
- Signal colours mean state. Never use one decoratively.
- Exactly one `data-gravity="hero"` card per screen.
- Every number is wrapped in `.o-num` or a metric class. Money and counts
  are right-aligned in tables.
- Status colour comes from `App\Support\Tone`. No colour literals in Blade.
- `.o-ring` is for single values only. Splits use `.o-meter`.
  Never add a donut chart or a chart library to this product.
- Empty states teach the concept. "No data" is not an acceptable string.
- Any new component must be added to the `/design` gallery in the same PR.
- Respect `prefers-reduced-motion`. Only two animations loop in the whole
  system: the overdue pulse and the live-phase breathe.

### Chrome is constant

The KPI strip, the bottom dock and the Command Center disc stay dark in
**both** themes. They use `--chrome`, not `--hull`. Fixed furniture that
changes colour when the theme switches makes the product feel unstable.

### Theme

**Light is the default.** Dark is for show days and live operations.
`App\Support\ThemePolicy` decides per module and prints the result into
`<html data-theme="...">`. Never hard-code a theme in a view. The ratio is
a single constant in that class — change it there, nowhere else.

### Order of work

Bottom-up, always: tokens -> components -> navigation -> screens.
Never rebuild a screen before the components it needs exist.
One phase per PR, behind a feature flag, with before/after screenshots.

See `CLAUDE-CODE-BRIEF.md` for the full phase plan and module checklist.
EOF

# ── 4. report ────────────────────────────────────────────────────────
say ""
say "${bold}Done.${off} Next steps:"
say ""
say "  1. Add the import lines to ${bold}resources/css/app.css${off}:"
say ""
say "         ${dim}@import './orbit-tokens.css';${off}"
say "         ${dim}@import 'tailwindcss';${off}"
say "         ${dim}@import './orbit-theme.css';${off}"
say "         ${dim}@import './orbit.css';${off}"
say ""
say "  2. Install the fonts:"
say ""
say "         ${dim}npm i @fontsource/inter @fontsource/jetbrains-mono @fontsource/instrument-serif${off}"
say ""
say "  3. Commit:"
say ""
say "         ${dim}git add -A && git commit -m 'chore: ORBIT tokens and guardrails'${off}"
say ""
say "  4. Open Claude Code and paste ${bold}Session 1${off} from KICKOFF-PROMPT.txt."
say ""
