<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    @php
        $fixColor = ['entrance' => '#0EA5E9', 'stage' => '#1E3352', 'registration' => '#6366F1', 'catering' => '#14B8A6', 'lounge' => '#B45309', 'info' => '#64748B', 'restrooms' => '#94A3B8', 'aisle' => '#CBD5E1'];
        $statusFill = ['available' => ['#FFFFFF', '#94A3B8'], 'reserved' => ['#FBF3DE', '#8A6D1F'], 'sold' => ['#E7F6EC', '#1F7A48']];
        $fmtM = fn ($n) => rtrim(rtrim(number_format((float) $n, 1), '0'), '.');
    @endphp
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; color: #1E3352; }
        .head { background: {{ $theme['primary'] }}; color: #fff; padding: 10px 20px; }
        .head .eyebrow { color: {{ $theme['accent'] }}; font-size: 8px; letter-spacing: 2px; text-transform: uppercase; font-weight: bold; }
        .head h1 { font-size: 15px; margin-top: 1px; }
        .hall { padding: 10px 20px 0; }
        .hall h2 { font-size: 12px; color: {{ $theme['primary'] }}; }
        .hall .dims { font-size: 9px; color: #64748B; margin-bottom: 6px; }
        .canvas { position: relative; border: 1px solid #C7D0DE; border-radius: 5px; background: #FFFFFF; margin: 0 auto; }
        .box { position: absolute; overflow: hidden; }
        .booth { border-radius: 3px; border-width: 1.5px; border-style: solid; text-align: center; }
        .booth .n { font-size: 6.5px; font-weight: bold; opacity: 0.8; }
        .booth .c { font-size: 7.5px; font-weight: bold; }
        .fx { border-radius: 3px; border-width: 1.5px; border-style: dashed; text-align: center; font-size: 6.5px; font-weight: bold; text-transform: uppercase; }
        .foot { text-align: center; font-size: 8px; color: #94A3B8; padding: 8px 0; }
    </style>
</head>
<body>
    <div class="head">
        <div class="eyebrow">&#9670; Elite Business Hub · Exhibition Floor Plan</div>
        <h1>{{ $event->name }}</h1>
        <div style="font-size:9px; margin-top:3px; color:#D7DEE9;">
            {{ $sales['sold'] }} of {{ $sales['total'] }} booths sold · revenue {{ $event->money($sales['soldValue']) }}
            @if ($sales['reserved'])· {{ $sales['reserved'] }} reserved ({{ $event->money($sales['pipelineValue']) }} pipeline)@endif
        </div>
    </div>

    @foreach ($halls as $hall)
        @php
            $W = $hall->width_m ?: 30;
            $L = $hall->length_m ?: 20;
            $scale = min(760 / $W, 400 / $L);
            $cw = round($W * $scale);
            $ch = round($L * $scale);
            $placed = $hall->booths;
            $fixtures = $hall->fixtures ?? [];
        @endphp
        <div class="hall" @if (! $loop->first) style="page-break-before: always;" @endif>
            <h2>{{ $hall->name }}</h2>
            <div class="dims">{{ $fmtM($W) }} × {{ $fmtM($L) }} m · {{ $fmtM($W * $L) }} m² · {{ $placed->count() }} booths ({{ $placed->filter(fn ($b) => $b->status() === 'sold')->count() }} sold)</div>
            <div class="canvas" style="width:{{ $cw }}px; height:{{ $ch }}px;">
                @foreach ($fixtures as $f)
                    @php $fc = $fixColor[$f['type']] ?? '#64748B'; $w = ($f['w'] ?? 3) * $scale; $h = ($f['h'] ?? 2) * $scale; $l = ($f['x'] ?? 0) * $scale - $w / 2; $t = ($f['y'] ?? 0) * $scale - $h / 2; @endphp
                    <div class="box fx" style="left:{{ round($l) }}px; top:{{ round($t) }}px; width:{{ round($w) }}px; height:{{ round($h) }}px; border-color:{{ $fc }}; color:{{ $fc }}; line-height:{{ round($h) }}px;">{{ $f['label'] }}</div>
                @endforeach
                @foreach ($placed as $b)
                    @php
                        $st = $b->status();
                        [$bg, $tx] = $statusFill[$st];
                        $w = $b->w_m * $scale; $h = $b->h_m * $scale; $l = $b->x * $scale - $w / 2; $t = $b->y * $scale - $h / 2;
                    @endphp
                    <div class="box booth" style="left:{{ round($l) }}px; top:{{ round($t) }}px; width:{{ round($w) }}px; height:{{ round($h) }}px; background:{{ $bg }}; border-color:{{ $tx }}; color:{{ $tx }}; {{ $st === 'available' ? 'border-style:dashed;' : '' }}">
                        @if ($h > 22)<div class="n" style="margin-top:2px;">{{ $b->number }}</div>@endif
                        <div class="c">{{ \Illuminate\Support\Str::limit($b->exhibitor?->company ?? ($b->price_cents ? $event->money($b->price_cents) : 'For sale'), 16) }}</div>
                    </div>
                @endforeach
            </div>
        </div>
    @endforeach

    <div class="foot">Generated by Elite Business Hub · {{ $event->name }} · drawn to metre scale</div>
</body>
</html>
