<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * 78 foreign-key columns with no index — mostly event_id on the event's
 * child tables, the single most common WHERE clause in this app. Every
 * hub tab scopes its query by event_id; without an index that's a full
 * table scan as each table grows across the whole portfolio, not just
 * one event.
 */
return new class extends Migration
{
    public function up(): void
    {
        $indexes = [
            ['event_supplier', 'supplier_id'],
            ['event_rooms', 'event_id'],
            ['event_agenda_days', 'event_id'],
            ['event_agenda_sessions', 'room_id'],
            ['event_agenda_sessions', 'agenda_day_id'],
            ['event_sponsors', 'event_id'],
            ['event_risks', 'owner_id'],
            ['event_risks', 'event_id'],
            ['event_approvals', 'decided_by'],
            ['event_approvals', 'requested_by'],
            ['event_team_members', 'user_id'],
            ['event_favorites', 'event_id'],
            ['event_speakers', 'event_id'],
            ['event_income_items', 'event_id'],
            ['event_budget_versions', 'decided_by'],
            ['event_budget_versions', 'requested_by'],
            ['event_budget_versions', 'event_id'],
            ['event_exhibitors', 'hall_id'],
            ['event_exhibitors', 'event_id'],
            ['event_briefs', 'event_id'],
            ['agenda_session_speaker', 'speaker_id'],
            ['event_booths', 'hall_id'],
            ['audit_logs', 'user_id'],
            ['event_contract_payments', 'contract_id'],
            ['event_contract_payments', 'event_id'],
            ['plan_items', 'approved_by'],
            ['plan_items', 'track_id'],
            ['plan_item_user', 'user_id'],
            ['plan_subtasks', 'owner_id'],
            ['tasks', 'track_id'],
            ['tasks', 'event_id'],
            ['tasks', 'assignee_id'],
            ['event_document_folders', 'parent_id'],
            ['event_documents', 'folder_id'],
            ['event_documents', 'uploaded_by'],
            ['events', 'venue_id'],
            ['events', 'project_id'],
            ['events', 'client_id'],
            ['events', 'project_manager_id'],
            ['transport_drivers', 'supplier_id'],
            ['transport_vehicles', 'supplier_id'],
            ['transport_vehicles', 'vehicle_type_id'],
            ['event_transport', 'supplier_id'],
            ['event_transport', 'vehicle_id'],
            ['event_transport', 'driver_id'],
            ['event_transport', 'event_id'],
            ['event_transport', 'vehicle_type_id'],
            ['event_transport', 'service_type_id'],
            ['deals', 'event_id'],
            ['deals', 'owner_id'],
            ['deals', 'contact_id'],
            ['deals', 'client_id'],
            ['deal_activities', 'user_id'],
            ['deal_activities', 'contact_id'],
            ['deal_activities', 'deal_id'],
            ['taxonomy_terms', 'parent_id'],
            ['event_room_blocks', 'venue_id'],
            ['event_room_blocks', 'supplier_id'],
            ['event_accommodations', 'venue_id'],
            ['event_accommodations', 'block_id'],
            ['event_accommodations', 'event_id'],
            ['event_accommodations', 'attendee_id'],
            ['event_transport_passengers', 'venue_id'],
            ['event_transport_passengers', 'event_id'],
            ['event_transport_passengers', 'attendee_id'],
            ['invoices', 'client_id'],
            ['invoices', 'contract_id'],
            ['invoice_lines', 'payment_id'],
            ['event_budget_items', 'supplier_id'],
            ['event_budget_items', 'room_id'],
            ['proposals', 'owner_id'],
            ['proposals', 'event_id'],
            ['proposals', 'contact_id'],
            ['proposals', 'client_id'],
            ['event_invoice_items', 'service_item_id'],
            ['event_catering_items', 'supplier_id'],
            ['event_catering_items', 'room_id'],
            ['event_catering_items', 'event_id'],
        ];

        foreach ($indexes as [$table, $column]) {
            Schema::table($table, fn (Blueprint $t) => $t->index($column));
        }
    }

    public function down(): void
    {
        $indexes = [
            ['event_supplier', 'supplier_id'],
            ['event_rooms', 'event_id'],
            ['event_agenda_days', 'event_id'],
            ['event_agenda_sessions', 'room_id'],
            ['event_agenda_sessions', 'agenda_day_id'],
            ['event_sponsors', 'event_id'],
            ['event_risks', 'owner_id'],
            ['event_risks', 'event_id'],
            ['event_approvals', 'decided_by'],
            ['event_approvals', 'requested_by'],
            ['event_team_members', 'user_id'],
            ['event_favorites', 'event_id'],
            ['event_speakers', 'event_id'],
            ['event_income_items', 'event_id'],
            ['event_budget_versions', 'decided_by'],
            ['event_budget_versions', 'requested_by'],
            ['event_budget_versions', 'event_id'],
            ['event_exhibitors', 'hall_id'],
            ['event_exhibitors', 'event_id'],
            ['event_briefs', 'event_id'],
            ['agenda_session_speaker', 'speaker_id'],
            ['event_booths', 'hall_id'],
            ['audit_logs', 'user_id'],
            ['event_contract_payments', 'contract_id'],
            ['event_contract_payments', 'event_id'],
            ['plan_items', 'approved_by'],
            ['plan_items', 'track_id'],
            ['plan_item_user', 'user_id'],
            ['plan_subtasks', 'owner_id'],
            ['tasks', 'track_id'],
            ['tasks', 'event_id'],
            ['tasks', 'assignee_id'],
            ['event_document_folders', 'parent_id'],
            ['event_documents', 'folder_id'],
            ['event_documents', 'uploaded_by'],
            ['events', 'venue_id'],
            ['events', 'project_id'],
            ['events', 'client_id'],
            ['events', 'project_manager_id'],
            ['transport_drivers', 'supplier_id'],
            ['transport_vehicles', 'supplier_id'],
            ['transport_vehicles', 'vehicle_type_id'],
            ['event_transport', 'supplier_id'],
            ['event_transport', 'vehicle_id'],
            ['event_transport', 'driver_id'],
            ['event_transport', 'event_id'],
            ['event_transport', 'vehicle_type_id'],
            ['event_transport', 'service_type_id'],
            ['deals', 'event_id'],
            ['deals', 'owner_id'],
            ['deals', 'contact_id'],
            ['deals', 'client_id'],
            ['deal_activities', 'user_id'],
            ['deal_activities', 'contact_id'],
            ['deal_activities', 'deal_id'],
            ['taxonomy_terms', 'parent_id'],
            ['event_room_blocks', 'venue_id'],
            ['event_room_blocks', 'supplier_id'],
            ['event_accommodations', 'venue_id'],
            ['event_accommodations', 'block_id'],
            ['event_accommodations', 'event_id'],
            ['event_accommodations', 'attendee_id'],
            ['event_transport_passengers', 'venue_id'],
            ['event_transport_passengers', 'event_id'],
            ['event_transport_passengers', 'attendee_id'],
            ['invoices', 'client_id'],
            ['invoices', 'contract_id'],
            ['invoice_lines', 'payment_id'],
            ['event_budget_items', 'supplier_id'],
            ['event_budget_items', 'room_id'],
            ['proposals', 'owner_id'],
            ['proposals', 'event_id'],
            ['proposals', 'contact_id'],
            ['proposals', 'client_id'],
            ['event_invoice_items', 'service_item_id'],
            ['event_catering_items', 'supplier_id'],
            ['event_catering_items', 'room_id'],
            ['event_catering_items', 'event_id'],
        ];

        foreach ($indexes as [$table, $column]) {
            Schema::table($table, fn (Blueprint $t) => $t->dropIndex([$column]));
        }
    }
};
