#!/usr/bin/env bash
#
# ORBIT v2 — repo bootstrap
# Elite Event Hub · Laravel + Livewire + Alpine + Tailwind
#
# Run this ONCE from your repo root, before you open Claude Code.
# It does the two things that must not be done by hand:
#
#   1. Extracts the design tokens and component CSS out of the design
#      system HTML, byte for byte. 100 tokens and 141 component classes.
#      An agent retyping those will introduce silent errors and break the
#      contrast guarantees.
#
#   2. Writes CLAUDE.md guardrails so the rules survive after you stop
#      watching the agent.
#
# It does NOT write any Blade, PHP or JS. That is Claude Code's job.
#
#   ./setup-orbit.sh              normal run
#   ./setup-orbit.sh --force      overwrite files that already exist
#   ./setup-orbit.sh --check      verify only, change nothing
#
set -euo pipefail

HTML="orbit-v2-hub-system.html"
FORCE=0
CHECK=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --check) CHECK=1 ;;
    -h|--help) sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

bold=$'\033[1m'; dim=$'\033[2m'; grn=$'\033[32m'; ylw=$'\033[33m'; red=$'\033[31m'; off=$'\033[0m'
say()  { printf '%s\n' "$*"; }
ok()   { printf '  %s✓%s %s\n' "$grn" "$off" "$*"; }
warn() { printf '  %s!%s %s\n' "$ylw" "$off" "$*"; }
die()  { printf '\n%serror:%s %s\n' "$red" "$off" "$*" >&2; exit 1; }

say ""
say "${bold}ORBIT v2 — repo bootstrap${off}"
say "${dim}extracts CSS from the design system, writes guardrails, touches nothing else${off}"
say ""

# ── 1. sanity ────────────────────────────────────────────────────────
say "${bold}Checking the repo${off}"

[ -f artisan ]      || die "no artisan file here. Run this from your Laravel repo root."
[ -f "$HTML" ]      || die "$HTML not found. Copy it into the repo root first."
[ -d resources/css ] || die "resources/css/ missing. Is this a standard Laravel app?"
ok "Laravel repo detected"
ok "$HTML found ($(wc -c < "$HTML" | tr -d ' ') bytes)"

if git rev-parse --git-dir >/dev/null 2>&1; then
  if [ -n "$(git status --porcelain)" ]; then
    warn "working tree is dirty"
    if [ "$CHECK" -eq 0 ] && [ "$FORCE" -eq 0 ]; then
      die "refusing to write into a dirty tree so you can always undo this.
       Commit or stash first, or re-run with --force if you know what you are doing."
    fi
  else
    ok "git working tree is clean"
  fi
else
  warn "not a git repo — you will not be able to undo this easily"
fi

# ── 2. extract ───────────────────────────────────────────────────────
TOK_START=':root, [data-theme="light"]{'
CMP_START='*,*::before,*::after{box-sizing'
CMP_STOP='.doc{display:grid;grid-template-columns:266px'

extract () { # $1 start marker, $2 stop marker
  awk -v start="$1" -v stop="$2" '
    index($0, start) { f = 1 }
    index($0, stop)  { f = 0 }
    f { print }
  ' "$HTML"
}

TOKENS="$(extract "$TOK_START" "$CMP_START")"
COMPS="$(extract "$CMP_START" "$CMP_STOP")"

[ -n "$TOKENS" ] || die "could not find the token block in $HTML — is it the v2 file?"
[ -n "$COMPS"  ] || die "could not find the component block in $HTML — is it the v2 file?"

TOKEN_COUNT=$(printf '%s' "$TOKENS" | grep -o -- '--[a-z0-9-]*:' | sort -u | wc -l | tr -d ' ')
CLASS_COUNT=$(printf '%s' "$COMPS" | grep -o -- '\.o-[a-z0-9_-]*' | sort -u | wc -l | tr -d ' ')
RULE_COUNT=$(printf '%s' "$COMPS" | grep -c '{' | tr -d ' ')

say ""
say "${bold}Extracted from the design system${off}"
ok "$TOKEN_COUNT design tokens"
ok "$CLASS_COUNT component classes"
ok "$RULE_COUNT CSS rules"

if [ "$CHECK" -eq 1 ]; then
  say ""
  say "${dim}--check: nothing written.${off}"
  exit 0
fi

# ── 3. write ─────────────────────────────────────────────────────────
write () { # $1 path, stdin body
  local path="$1"
  if [ -f "$path" ] && [ "$FORCE" -eq 0 ]; then
    warn "$path exists — skipped (use --force to overwrite)"
    cat > /dev/null
    return
  fi
  mkdir -p "$(dirname "$path")"
  cat > "$path"
  ok "wrote $path"
}

say ""
say "${bold}Writing files${off}"

{
  cat <<'HDR'
/* ═══════════════════════════════════════════════════════════════════════
   ORBIT DESIGN SYSTEM v2.0 — TOKENS
   GENERATED by setup-orbit.sh from orbit-v2-hub-system.html
   Do not edit by hand. Edit the HTML and re-run the script.
   ─────────────────────────────────────────────────────────────────────
   Theme switches by setting data-theme="light|dark" on <html>.
   Both themes define IDENTICAL variable names, so no component ever
   needs a dark variant.

   DO NOT CHANGE COLOUR VALUES. Every accent and signal colour has been
   measured against every surface it can appear on — 48 pairs per theme,
   all meaningful colours at or above 4.5:1 (WCAG AA). Changing one hex
   breaks that guarantee silently.
   ═══════════════════════════════════════════════════════════════════ */

HDR
  printf '%s\n' "$TOKENS"
} | write resources/css/orbit-tokens.css

{
  cat <<'HDR'
/* ═══════════════════════════════════════════════════════════════════════
   ORBIT DESIGN SYSTEM v2.0 — COMPONENTS
   GENERATED by setup-orbit.sh from orbit-v2-hub-system.html
   Do not edit by hand. Edit the HTML and re-run the script.
   ─────────────────────────────────────────────────────────────────────
   Requires orbit-tokens.css to be imported first.
   Class prefix: .o-
   If you need a value that is not a token, the answer is a new token,
   not a literal.
   ═══════════════════════════════════════════════════════════════════ */

HDR
  printf '%s\n' "$COMPS"
} | write resources/css/orbit.css

write resources/css/orbit-theme.css <<'EOF'
/* Tailwind wiring — import AFTER tailwindcss in app.css.
   Exposes ORBIT tokens as Tailwind theme values so utilities and
   components read from one source. */

@theme {
  --color-canvas:   var(--abyss);
  --color-surface:  var(--hull);
  --color-raised:   var(--deck);
  --color-rim:      var(--rim);
  --color-rim-hi:   var(--rim-hi);
  --color-ink:      var(--ink);
  --color-ink-2:    var(--ink-2);
  --color-ink-3:    var(--ink-3);
  --color-ink-4:    var(--ink-4);
  --color-iris:     var(--iris);
  --color-iris-2:   var(--iris-2);
  --color-gold:     var(--gold);
  --color-vital:    var(--vital);
  --color-ion:      var(--ion);
  --color-flare:    var(--flare);
  --color-critical: var(--critical);

  --font-display: 'Instrument Serif', Georgia, serif;
  --font-sans:    'Inter', system-ui, -apple-system, sans-serif;
  --font-mono:    'JetBrains Mono', ui-monospace, SFMono-Regular, monospace;

  --radius-xs: 8px;  --radius-sm: 11px; --radius-md: 16px;
  --radius-lg: 22px; --radius-xl: 30px;
}

/* Documents always print light and without chrome. */
@media print {
  html { --void:#fff; --abyss:#fff; --hull:#fff; --plate:#fff; --deck:#fff; }
  .o-dock, .o-arc, .o-topbar, .o-twin__tools, .o-ai { display: none !important; }
  .o-panel, .o-card { box-shadow: none !important; break-inside: avoid; }
}
EOF

write CLAUDE.md <<'EOF'
# Elite Event Hub — working agreement

## Design system: ORBIT v2

The visual specification is `orbit-v2-hub-system.html` in the repo root.
Open it and read the CSS in its `<style>` block. That file is the source
of truth for every colour, size, radius, shadow and class name.

`resources/css/orbit-tokens.css` and `resources/css/orbit.css` are
**generated** from that HTML by `setup-orbit.sh`. Never edit them by hand.
If a token genuinely needs to change, change the HTML and re-run the script.

### Hard rules

- Never introduce a colour, radius, shadow, font-size, spacing value or
  transition duration that is not already a token.
- **Iris** (`--iris`) is the only action colour: primary buttons, focus
  rings, active nav, selected tabs, progress fills, links, AI surfaces.
- **Gold** (`--gold`) is prestige only: brand mark, VIP tier, premium
  sponsor, exported document headers. Never a button, focus ring or status.
- Maximum 3 gold elements per viewport.
- Exactly one `data-gravity="hero"` card per screen.
- Every number rendered in the UI is wrapped in `.o-num` or a metric class
  (`.o-metric`, `.o-metric-sm`, `.o-metric-lg`). Money and counts are
  right-aligned in tables.
- Status colour comes from `App\Support\Tone`. No colour literals in Blade.
- `.o-ring` is for single values only. Splits use `.o-meter`.
  Never add a donut chart to this product.
- Empty states teach the concept. "No data" is not an acceptable string.
- Any new component must be added to the `/design` gallery in the same PR.
- Respect `prefers-reduced-motion`. Only two animations loop in the whole
  system: the overdue pulse and the live-phase breathe.

### Theme

Light is the default and covers roughly 70% of screens. Dark is for live
operations. `App\Support\ThemePolicy` decides, and prints the result into
`<html data-theme="...">`. Never hard-code a theme in a view.

### Order of work

Bottom-up, always: tokens → components → navigation → screens.
Never rebuild a screen before the components it needs exist.
One phase per PR, behind a feature flag, with before/after screenshots.

See `CLAUDE-CODE-BRIEF.md` for the full phase plan.
EOF

# ── 4. report ────────────────────────────────────────────────────────
say ""
say "${bold}Done.${off} Next steps:"
say ""
say "  1. Add the import lines to ${bold}resources/css/app.css${off}:"
say ""
say "         ${dim}@import './orbit-tokens.css';${off}"
say "         ${dim}@import 'tailwindcss';${off}"
say "         ${dim}@import './orbit-theme.css';${off}"
say "         ${dim}@import './orbit.css';${off}"
say ""
say "  2. Install the fonts:"
say ""
say "         ${dim}npm i @fontsource/inter @fontsource/jetbrains-mono @fontsource/instrument-serif${off}"
say ""
say "  3. Commit:"
say ""
say "         ${dim}git add -A && git commit -m 'chore: ORBIT v2 tokens and guardrails'${off}"
say ""
say "  4. Open Claude Code and paste ${bold}KICKOFF-PROMPT.txt${off}."
say ""
